#!/bin/sh

#
# Start a busybox LXC container with the container's name in the shell prompt
#

if [ $# -ne 1 ]
then echo "Usage: `basename $0` container_name" >&2
     exit 1
fi

lxc-start -n $1 -s lxc.environment=PS1=\\h\#\\x20
